**Assignment-1: NumPy**

In [3]:
import numpy as np

1. Create a null vector of size 10 but the fifth value which is 1.

In [4]:
null_vector = np.zeros(10)
null_vector[4] = 1
print("Null vector of size 10 with the fifth value as 1: ", null_vector)

Null vector of size 10 with the fifth value as 1:  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


2. Create a vector with values ranging from 10 to 49.

In [5]:
vector = np.arange(10, 50)
print("Vector with values ranging from 10 to 49: ", vector)

Vector with values ranging from 10 to 49:  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3. Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
matrix = np.arange(0, 9).reshape(3, 3)
print("3x3 matrix with values ranging from 0 to 8: \n", matrix)

3x3 matrix with values ranging from 0 to 8: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [7]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print("Indices of non-zero elements from [1,2,0,0,4,0]: ", non_zero_indices)

Indices of non-zero elements from [1,2,0,0,4,0]:  (array([0, 1, 4]),)


5. Create a 10x10 array with random values and find the minimum and maximum values.

In [8]:
array = np.random.rand(10, 10)
min_val = np.min(array)
max_val = np.max(array)
print("10x10 array with random values: \n", array)
print("Minimum value: ", min_val)
print("Maximum value: ", max_val)

10x10 array with random values: 
 [[0.17740894 0.57928011 0.2069229  0.46819193 0.25075462 0.95959354
  0.43438529 0.02766828 0.77854852 0.27585283]
 [0.78417741 0.29996643 0.13636571 0.5296828  0.54427109 0.72978109
  0.63561675 0.16470936 0.01619121 0.21125119]
 [0.2117895  0.31439422 0.15437708 0.93873517 0.46659294 0.82533554
  0.05748279 0.85044593 0.47116733 0.57932314]
 [0.35182174 0.60868954 0.02052261 0.05098165 0.82519736 0.98197743
  0.96538555 0.98923171 0.6640837  0.75694834]
 [0.47382286 0.45728844 0.89218809 0.43755195 0.28174384 0.95026385
  0.4370097  0.2191619  0.47999426 0.08973063]
 [0.11953078 0.11135614 0.61336643 0.00848956 0.70826014 0.60425555
  0.07764366 0.75233149 0.04411564 0.1848576 ]
 [0.78798086 0.0827253  0.90038098 0.8846169  0.32820853 0.695628
  0.8883527  0.94225568 0.12197422 0.89605274]
 [0.69873699 0.43844929 0.12266029 0.14751282 0.59933354 0.98993569
  0.4146051  0.52717335 0.31765931 0.09631794]
 [0.68965757 0.91788505 0.32549532 0.73973978 0.

6. Create a random vector of size 30 and find the mean value.

In [9]:
random_vector = np.random.rand(30)
mean_value = np.mean(random_vector)
print("Random vector of size 30: ", random_vector)
print("Mean value: ", mean_value)

Random vector of size 30:  [0.06376209 0.67129307 0.03072544 0.86509415 0.97214354 0.96687144
 0.65209159 0.66386522 0.54367527 0.54095009 0.1875014  0.89815856
 0.0697913  0.93227309 0.09368711 0.85649792 0.41977849 0.18011482
 0.21310084 0.54269484 0.36993219 0.70546203 0.90618543 0.1769557
 0.39409397 0.24185985 0.22071335 0.80373636 0.0187751  0.85880632]
Mean value:  0.5020196860054413
